### ISSUE TITLE
Validate

### ISSUE THREAD

**Issue by Midnighter** [zakandrewking/escher#311]
Hi, I just hit the same bug as in #83 and #150. However, it was not clear to me what the resolution is. Are you not going to fix this?

Currently using
```
Escher==1.7.0b14
Python 3.6.7
```
and the command 

```bash
python -m escher.validate mymap.json
```
fails with 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/moritz/.virtualenvs/carrot/lib/python3.6/site-packages/escher/validate.py", line 130, in <module>
    main()
  File "/home/moritz/.virtualenvs/carrot/lib/python3.6/site-packages/escher/validate.py", line 27, in main
    validate_map(map_data)
  File "/home/moritz/.virtualenvs/carrot/lib/python3.6/site-packages/escher/validate.py", line 34, in validate_map
    schema = get_jsonschema()
  File "/home/moritz/.virtualenvs/carrot/lib/python3.6/site-packages/escher/validate.py", line 106, in get_jsonschema
    with open(get_filepath('map_jsonschema'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/moritz/.virtualenvs/carrot/lib/python3.6/site-packages/escher/static/jsonschema/1-0-0'
```

**Comment by matthiaskoenig** [comment]
I am pretty sure the `py/MANIFEST.in` patterns are incorrect.
```
recursive-include escher/static *.*
recursive-include escher/templates *.*
include escher.json
```
Should be 
```
recursive-include escher/static *
recursive-include escher/templates *
include escher.json
```
These are unix style glob patterns.
As a workaround until an updated pip release with the resources is available you can just clone the project in install it from the py folder with `pip install -e .`, which should work because resources are in the cloned repository.

To lazy to make a pull request for this, also requires a new pip release to make the package with resources available.

**Comment by Midnighter** [comment]
Cheers, I'll try it out and maybe make a PR.

**Comment by zakandrewking** [comment]
let me know if it works. i'm happy to include it in the 1.7 release
