### ISSUE TITLE
Conda install escher : could not find the {kind} {name} on the server

### ISSUE THREAD

**Issue by picousse** [zakandrewking/escher#316]
hi,
I'm trying  to install escher in a conda (python 3.5) env.
however I get this error:

```
>>> import escher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/cameo/lib/python3.5/site-packages/escher/__init__.py", line 11, in <module>
    from escher.plots import (
  File "/opt/miniconda/envs/cameo/lib/python3.5/site-packages/escher/plots.py", line 71
    raise Exception(f'Could not find the {kind} {name} on the server')
                                                                    ^
SyntaxError: invalid syntax
```

```
conda install pip
pip install escher
```

**Comment by zakandrewking** [comment]
Thanks for reporting! This is a simple fix. You can track the progress in #317.

**Comment by zakandrewking** [comment]
Should be good to go with version 1.7.2

**Comment by picousse** [comment]
that's fast!
Thanks!
