### ISSUE TITLE
installing escher jupyter notebook extension

### ISSUE THREAD

**Issue by glucksfall** [zakandrewking/escher#321]
Hello,

I found this error when trying to install the jupyter notebook extension

```
$jupyter nbextension install --py escher
Traceback (most recent call last):
  File "/shared/D1/opt/python-3.6.5/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/shared/D1/opt/python-3.6.5/lib/python3.6/site-packages/notebook/nbextensions.py", line 1125, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module escher is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
```

It seems doesn't impact escher usability (I thought I couldn't see anything when called the Builder, but I forgot to add the display_in_notebook() at the end)

**Comment by zakandrewking** [comment]
Can you share the jupyter notebook and escher versions you are using? 

`pip list|grep notebook`
`pip list|grep escher`

**Comment by glucksfall** [comment]
notebook version 6.0.0 and escher version 1.6.0

**Comment by glucksfall** [comment]
PS: it is installed as Escher

**Comment by zakandrewking** [comment]
You'll need the latest Escher version - try 1.7.3

**Comment by glucksfall** [comment]
Yes, that solved the issue. Thank you
