### ISSUE TITLE
Using old maps

### ISSUE THREAD

**Issue by jotech** [zakandrewking/escher#82]
Maps made with escher <v1.0 do not seem to work in the new release.
[example](http://homepages.uni-jena.de/~xo37cot/sm-redox.json)

**Comment by jotech** [comment]
@zakandrewking sorry for my late reply!
It's working very well now ;o)
Thank's a lot.

**Comment by meono** [comment]
Hi Zak,
I also have map that fails to convert with the tool (I am on 1.1.0). The error is as follows:

```
Traceback (most recent call last):
  File "/Users/emre/Dev/escher/escher/convert_map.py", line 258, in <module>
    main()
  File "/Users/emre/Dev/escher/escher/convert_map.py", line 67, in main
    the_map = convert(out, model)
  File "/Users/emre/Dev/escher/escher/convert_map.py", line 254, in convert
    validate_map(the_map) 
  File "/Users/emre/.virtualenvs/modeling/lib/python2.7/site-packages/Escher-1.1.0-py2.7.egg/escher/validate.py", line 15, in validate_map
    jsonschema.validate(map_data, schema)
  File "/Users/emre/.virtualenvs/modeling/lib/python2.7/site-packages/jsonschema/validators.py", line 428, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/Users/emre/.virtualenvs/modeling/lib/python2.7/site-packages/jsonschema/validators.py", line 117, in validate
    raise error
jsonschema.exceptions.ValidationError: u'7620' is not of type u'number'

Failed validating u'type' in schema[u'items'][1][u'properties'][u'reactions'][u'patternProperties'][u'[0-9]+'][u'properties'][u'label_x']:
    {u'type': u'number'}

On instance[1][u'reactions'][u'1330603'][u'label_x']:
    u'7620'
```

Any help on fixing it would be appreciated.

map and model are available at https://www.dropbox.com/sh/tvq393eh23ltcs4/AACd87Cw0drvH5aP0KbFXbxfa?dl=0

**Comment by zakandrewking** [comment]
I was able to fix this map. Here is a working file:  

https://www.dropbox.com/s/07ua328xrnviwy6/escher_issue82_fixed_map.json?dl=0

For the future, here are the fixes I made. Should be incorporated into convert_map.py:

```python
import cobra.io
from escher.convert_map import convert
import json

m = cobra.io.load_json_model('Ec_iAF1260_flux1.json')
with open('iAF1260_COMBINED.json', 'r') as f: themap = json.load(f)

themap['text_labels'] = {}

for r in themap['reactions'].values():
    r['label_x'] = float(r['label_x'])
    r['label_y'] = float(r['label_y'])
    for s in r['segments'].values():
        for b in ['b1', 'b2']:
            if s[b] is not None and (s[b]['x'] is None or s[b]['y'] is None):
                s[b] = None

out = convert(themap.copy(), m)
with open('out.json', 'w') as f: json.dump(out, f)
```

I'll reopen the issue until they are done.

**Comment by meono** [comment]
Thanks!
